### ISSUE TITLE
Receiving 404 response code when opening websocket connection

### ISSUE THREAD

**Issue by countach74** [zeekay/flask-uwsgi-websocket#38] opened 2015-10-05 15:55 UTC
I've been trying to get this module working, but every time I run into a 404 issue. This happens with each one of the gevent examples. (I haven't tried non-gevent.) Not sure what else to include except for packages and versions:

Flask==0.10.1
Flask-uWSGI-WebSocket==0.4.5
gevent==1.0.2
greenlet==0.4.9
itsdangerous==0.24
Jinja2==2.8
MarkupSafe==0.23
uWSGI==2.0.11.1
Werkzeug==0.10.4

Any help would be much appreciated!

**Comment by Ivoz** [comment] 2015-10-05 23:11
Same, I ran

```
$ uwsgi --master --http :5000 --http-websockets --gevent 100 --wsgi chat:app
```

and got as a log

```
GET /websocket => generated 233 bytes in 10 msecs (HTTP/1.1 404) 2 headers in 72 bytes (3 switches on core 99)
```

**Comment by gevatter** [comment] 2015-10-07 09:08
I can reproducte this, after downgrading to 0.4.4 the examples are running.

**Comment by mckabi** [comment] 2015-10-11 21:49
Same problem flask-uwsgi-websocket==0.4.5 with below exception:
```
examples/echo $ env/bin/python echo.py
...snip...
Traceback (most recent call last):
  File "examples/echo/env/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "examples/echo/env/lib/python2.7/site-packages/flask_uwsgi_websocket/websocket.py", line 70, in __call__
    raise e
werkzeug.exceptions.NotFound: 404: Not Found
[pid: 95947|app: 0|req: 1/1] 127.0.0.1 () {40 vars in 839 bytes} [Mon Oct 12 05:36:57 2015] GET / => generated 0 bytes in 1 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
```

Could not access any routing point of app.url_map, but ws.url_map is OK.

flask-uwsgi-websocket==0.4.4 is OK with same code and env.

**Comment by cyc60** [comment] 2015-10-16 11:35
+1, same problem with 0.4.5

**Comment by hitigon** [comment] 2015-10-28 23:30
looks like the previous commits with werkzeug url processors did not apply the same logic as Websocket for Gevent websocket middle.

did some patches from my fork using code from websocket, [check this commit](https://github.com/hitigon/flask-uwsgi-websocket/commit/785f4ebbf144479c91fc0ff47925016a90c8d079)

**Comment by zeekay** [comment] 2015-10-29 00:04
Does that rectify your issue? Having some issues after re-installing. Can you do a PR?

**Comment by hitigon** [comment] 2015-10-29 00:20
@zeekay did another commit to fix Websocket middleware as well, basically, (Map) urls.match() would fail and raise 404 not found since the WebsocketMiddleware was called twice (for the demos) from both websocket request and http request (the demo page). What i did is just to silence the exception instead of raising the error.

**Comment by zeekay** [comment] 2015-10-29 15:47
This should be fixed by @hitigon's PR.

**Closed by zeekay** 2015-10-29 15:47 UTC

**Comment by countach74** [comment] 2015-10-29 15:50
It probably is. I haven't had a chance to test it yet. Will try to do that
soon.

**Comment by zeekay** [comment] 2015-10-29 15:51
I manually tested briefly, seems to have resolved things. Really need to add a simple test suite....
